# Generated by Django 4.2.5 on 2023-10-13 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='topics',
            field=models.ManyToManyField(to='course.topic'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.topic'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='course',
            table='course_courses',
        ),
        migrations.AlterModelTable(
            name='lesson',
            table='course_lessons',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='course_topics',
        ),
    ]
