# Generated by Django 4.2.5 on 2023-10-13 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_topics_lesson_topic_alter_course_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
