# Generated by Django 4.2.5 on 2023-10-13 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course',
        ),
        migrations.RemoveField(
            model_name='respondentanswer',
            name='course',
        ),
    ]
