# Generated by Django 4.2.5 on 2023-10-13 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0002_remove_question_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='respondent',
            options={},
        ),
        migrations.AlterModelOptions(
            name='respondentanswer',
            options={},
        ),
        migrations.AlterModelTable(
            name='answer',
            table='estimator_answers',
        ),
        migrations.AlterModelTable(
            name='respondent',
            table='estimator_respondents',
        ),
        migrations.AlterModelTable(
            name='respondentanswer',
            table='estimator_respondent_answers',
        ),
    ]
