# Generated by Django 4.2.5 on 2023-10-13 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_description_course_image'),
        ('estimator', '0003_alter_answer_options_alter_respondent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondent',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='course.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='estimator.question'),
        ),
    ]
