# Generated by Django 4.2.5 on 2023-10-13 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estimator', '0004_respondent_course_alter_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='respondentanswer',
            name='respondent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='respondent_answers', to='estimator.respondent'),
            preserve_default=False,
        ),
    ]
